"""revork and add model8

Revision ID: 4b56869cd1a7
Revises: cf0333619d64
Create Date: 2024-11-20 15:20:57.358197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b56869cd1a7'
down_revision: Union[str, None] = 'cf0333619d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('poll_id', sa.Integer(), nullable=False))
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'answers', 'polls', ['poll_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.alter_column('answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('answers', 'poll_id')
    # ### end Alembic commands ###
