"""revork and add model4

Revision ID: 7987b05d7137
Revises: 0479f726d893
Create Date: 2024-11-19 17:26:30.340284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7987b05d7137'
down_revision: Union[str, None] = '0479f726d893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('polls', 'aboba')
    op.add_column('questions', sa.Column('current_answer', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'current_answer')
    op.add_column('polls', sa.Column('aboba', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('answers')
    # ### end Alembic commands ###
