"""revork and add model7

Revision ID: cf0333619d64
Revises: b0a10205f95a
Create Date: 2024-11-20 15:00:18.968134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0333619d64'
down_revision: Union[str, None] = 'b0a10205f95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'question_id')
    # ### end Alembic commands ###
